=== syamantm/Semblog/semblog.tstore/src/main/resources/scoreFactor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://jaxb.semblog.sw.ecs.soton.uk.ac/"
	xmlns="http://jaxb.semblog.sw.ecs.soton.uk.ac/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="scoreFactorType">
		<xsd:sequence>
			<xsd:element name="scoreFactorBean" type="xsd:string"
				minOccurs="1" maxOccurs="1" />

			<xsd:element name="defaultWeightage" type="xsd:double"
				minOccurs="1" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="scoreFactor">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="scoreFactor" type="scoreFactorType"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== syamantm/Semblog/semblog.tstore/conf/scoreFactorConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2011 sp1 (http://www.altova.com)-->
<!--
CoffeeType -> Latte; Min Price -> makeCoffeeServiceBinding01
CoffeeType -> Expresso; Min Price -> makeCoffeeServiceBinding02
CoffeeType -> Caffuccino; Min Price -> makeCoffeeServiceBinding03 
	 -->
<n1:scoreFactor xsi:schemaLocation="http://jaxb.semblog.sw.ecs.soton.uk.ac/scoreFactor.xsd" xmlns:n1="http://jaxb.semblog.sw.ecs.soton.uk.ac/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<scoreFactor>
		<scoreFactorBean>dateScoreFactor</scoreFactorBean>		
		<defaultWeightage>0.4</defaultWeightage>
	</scoreFactor>
	<scoreFactor>
		<scoreFactorBean>predicateScoreFactor</scoreFactorBean>		
		<defaultWeightage>0.3</defaultWeightage>
	</scoreFactor>
	<scoreFactor>
		<scoreFactorBean>vectorDistanceScoreFactor</scoreFactorBean>		
		<defaultWeightage>0.3</defaultWeightage>
	</scoreFactor>
	
</n1:scoreFactor>
